### ISSUE TITLE
Button type doesn't trigger keyboard modality

### ISSUE THREAD

**Issue by skosito** [WICG/focus-visible#228] opened 2020-05-14 18:00 UTC
Hey,

i noticed sometimes, since first element in app is button, classes are not added. I figured by reading and debugging focus-visible that reason is focusTriggersKeyboardModality method is not supporting buttons, so pretty much if we didn't have keyboard events before, and this method returns false, that button is skipped when pressing tab from url bar. 

Is there a way to add support for button type, or some workaround (i can always add content-editable to button to make it work, but that is hack and messes up with button :)). Also, I can not convert button to input type button (either way it seems that type is not whitelisted).

Thanks in advance

**Comment by skosito** [comment] 2020-05-16 01:19
Create PR for this issue, could you please take a look and tell me if this change would be ok? https://github.com/WICG/focus-visible/pull/229

**Comment by robdodson** [comment] 2020-05-20 19:39
Discussed over in #229. I believe this is working as intended. Going to close this issue but happy to keep discussing if there's any confusion.

**Closed by robdodson** 2020-05-20 19:39 UTC

**Comment by skosito** [comment] 2020-05-20 22:31
Thank you very much! Implemented a workaround for this specific case in my project.
